20200301_review_user interface_module_stage
trazzos/obras_frontend pull request #9
Opened 2020-03-01 16:33 UTC by aristasoluciones

2020-03-01 19:21 UTC, mwleinad requested changes
No vi muchos detalles malos, en general esta bien.

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/api/stageCreateApi.js
> +export default async function createStage (data) {
igual no tan importante pero yo llamaria esta funcion createStageApi, como el nombre del archivo asi es mas facil localizarla

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/api/stageCreateApi.js
> +   return error.response
porque el cambio aqui y no en stageDeleteApi por ejemplo?

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/CActionStage.vue
> +<template>
De entrada el nombre del archivo, que es la C? o la pusiste de mas?
De cualquier forma si es alguna abreviacion mejor usar la palabra correcta.

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/CFormStage.vue
> +<template>
no, ya vi que si significa algo la c jaja

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/CFormStage.vue
> +    mounted () {
si no necesitas esto mejor quitarlo

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/CFormStage.vue
> +    methods: {
igual

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/CModalStage.vue
> +        return (this.current_stage_index === -1) ? 'Agregar etapa' : 'Editar etapa'
porque -1 y no null?

2020-03-01 19:21 UTC, mwleinad commented on src/views/stage/components/task/CActionTask.vue
> +<template>
no este componente es practicamente igual al de stage? 
yo creo que habria alguna forma de crear un componente global no?

2020-03-03 19:58 UTC, aristasoluciones commented on src/views/stage/components/CFormStage.vue
> +    mounted () {
entendido,  metodos y funciones vacios se eliminan

2020-03-03 19:58 UTC, aristasoluciones commented on src/views/stage/components/CModalStage.vue
> +        return (this.current_stage_index === -1) ? 'Agregar etapa' : 'Editar etapa'
me cambie a null

2020-03-03 20:00 UTC, aristasoluciones commented on src/views/stage/components/task/CActionTask.vue
> +<template>
en views se creo una carpeta global/components , dentro se almacenaran componentes reutilizables en todo el proyecto.  hay dos componentes ahora, una para actiones de fila y otra para acciones de modal.

2020-03-03 20:49 UTC, mwleinad requested changes

2020-03-03 20:49 UTC, mwleinad commented on src/modules/globalModule.js
> +    state.snackbar.type = response.type
porque necesitas un type?

2020-03-04 23:25 UTC, mwleinad approved these changes

2020-03-04 23:25 UTC, merged